[package]
name = "op-rpc-types"
description = "Optimism RPC types"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["rlp", "serde", "std"] }
